### PR TITLE
add aarch64 build

### PR DESCRIPTION
**Pull request by adrianinsaval**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adrianinsaval** [comment]
any clue on why it's trying to use python 2.7?

**Comment by antony-jr** [comment]
> any clue on why it's trying to use python 2.7?

Now we know why it need python2, pyside2 is only supported on python2

**Comment by adrianinsaval** [comment]
> > any clue on why it's trying to use python 2.7?
> 
> Now we know why it need python2, pyside2 is only supported on python2

that's not true, pyside2 can be used with python3 too. It even says that there are installable packages

**Comment by adrianinsaval** [comment]
It keeps trying to use python 3.12 but pyside is not compatible with that. I don't know why it can't just use what I'm telling it to:

> Could not solve for environment specs
> The following packages are incompatible
> 
> ├─ pyside2 5.15.*  is installable with the potential options
> │  ├─ pyside2 [5.15.4|5.15.5|5.15.6|5.15.7|5.15.8] would require
> │  │  └─ python_abi 3.10.* *_cp310, which can be installed;
> │  ├─ pyside2 [5.15.4|5.15.5|5.15.6] would require
> │  │  └─ python_abi 3.7.* *_cp37m, which can be installed;
> │  ├─ pyside2 [5.15.4|5.15.5|5.15.6|5.15.7|5.15.8] would require
> │  │  └─ python_abi 3.8.* *_cp38, which can be installed;
> │  ├─ pyside2 [5.15.4|5.15.5|5.15.6|5.15.7|5.15.8] would require
> │  │  └─ python_abi 3.9.* *_cp39, which can be installed;
> │  └─ pyside2 [5.15.6|5.15.7|5.15.8] would require
> │     └─ python_abi 3.11.* *_cp311, which can be installed;
> └─ python >=3.12,<3.13.0a0  is not installable because it requires
>    └─ python_abi 3.12.* *_cp312, which conflicts with any installable versions previously reported.
>

**Comment by adrianinsaval** [comment]
why on earth is it hell bent on using python 3.12 🫠

**Comment by adrianinsaval** [comment]
@looooo have you got any idea what I have to do to make the test use python < 3.12?

**Comment by antony-jr** [comment]
The build log shows that we are only installing (even though you specify 3.10),
```
python:                    3.12.0-hab00c5b_0_cpython conda-forge
```

**Comment by looooo** [comment]
> > any clue on why it's trying to use python 2.7?
> 
> Now we know why it need python2, pyside2 is only supported on python2

this is a false assumption. pyside2 is not available for python3.12. This is the main issue here I guess.

> @looooo have you got any idea what I have to do to make the test use python < 3.12?

No, sry. I guess you did it the right way, but no idea why this is not working. Maybe temporally removing the tests and bring it back once we have updated this to qt6/pyside6. But maybe keep the checking for the libQAppImageUpdate.so file, so the linter is satisfied.

```
  commands:
    - test -f ${PREFIX}/plugins/libQAppImageUpdate.so
```

**Pull request merged**
